import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import "../card_rules.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const escape = text => text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const inline = text => escape(text)
  .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, href) => `<a href="${href === 'RULES.md' ? 'rules.html' : href === 'PLAYER_GUIDE.md' ? 'player_guide.html' : href}">${label}</a>`)
  .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
  .replace(/`([^`]+)`/g, "<code>$1</code>");

// The small Markdown subset used by the two rule documents; no runtime fetch.
function render(markdown) {
  const lines = markdown.trim().split(/\r?\n/);
  const result = [];
  for (let i = 0; i < lines.length;) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }
    const heading = line.match(/^(#{1,3}) (.+)$/);
    if (heading) { result.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`); i++; continue; }
    if (line.startsWith("|")) {
      const rows = [];
      while (i < lines.length && lines[i].startsWith("|")) rows.push(lines[i++].split("|").slice(1, -1).map(x => x.trim()));
      result.push(`<table><thead><tr>${rows[0].map(c => `<th>${inline(c)}</th>`).join("")}</tr></thead><tbody>${rows.slice(2).map(row => `<tr>${row.map(c => `<td>${inline(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`);
      continue;
    }
    if (/^(\d+\. |- )/.test(line)) {
      const ordered = /^\d/.test(line), tag = ordered ? "ol" : "ul", pattern = ordered ? /^\d+\. / : /^- /;
      const items = [];
      while (i < lines.length && pattern.test(lines[i])) items.push(`<li>${inline(lines[i++].replace(pattern, ""))}</li>`);
      result.push(`<${tag}>${items.join("")}</${tag}>`); continue;
    }
    const paragraph = [];
    while (i < lines.length && lines[i].trim() && !/^(#|\||\d+\. |- )/.test(lines[i])) paragraph.push(lines[i++]);
    if (!paragraph.length) throw new Error(`Unsupported Markdown: ${line}`);
    result.push(`<p>${inline(paragraph.join(" "))}</p>`);
  }
  return result.join("\n");
}

function page(title, body, source, condensed) {
  return `<!doctype html>
<!-- Generated by scripts/build_guides.mjs from ${source}; edit the Markdown source. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>
<style>
:root{color-scheme:light;--ink:#242b27;--accent:#356052;--line:#cbd6ce}*{box-sizing:border-box}body{margin:0;background:#f0f2ed;color:var(--ink);font:16px/1.5 Georgia,serif}nav{max-width:1040px;margin:24px auto;padding:0 28px;display:flex;gap:20px;font:14px/1.5 system-ui}a{color:var(--accent)}main{max-width:1040px;margin:0 auto 40px;padding:32px 44px 44px;background:#fffefa;border:1px solid var(--line)}h1,h2,h3,th{font-family:system-ui,sans-serif}h1{margin:0 0 22px;font-size:34px;letter-spacing:-1px}h2{font-size:18px;margin:24px 0 10px;color:var(--accent);break-after:avoid}h3{font-size:16px}p{margin:10px 0}ul,ol{padding-left:23px;margin:10px 0}li{margin:5px 0}table{width:100%;border-collapse:collapse;font-size:14px;margin:12px 0}th{text-align:left;background:#edf2ec}td,th{padding:8px 10px;border:1px solid var(--line);vertical-align:top}tr{break-inside:avoid}strong{font-weight:700}footer{margin-top:24px;border-top:1px solid var(--line);padding-top:12px;font:12px system-ui;color:#59675d}.condensed{font-size:15px}.condensed h2{margin-top:20px}@media(max-width:650px){nav{flex-wrap:wrap;margin:16px auto;padding:0 18px;gap:12px}main{padding:24px 18px;border:0}h1{font-size:28px}table{font-size:12px}td,th{padding:6px}}@page{size:A4;margin:13mm}@media print{body{background:white;font-size:10pt;line-height:1.35}nav,footer{display:none}main{border:0;padding:0;margin:0;max-width:none}.condensed{font-size:9.5pt}h1{font-size:23pt;margin-bottom:12pt}h2,.condensed h2{font-size:12pt;margin:13pt 0 6pt}p,ul,ol{margin:6pt 0}li{margin:3pt 0}table{font-size:9pt;margin:7pt 0}td,th{padding:5pt}a{color:inherit;text-decoration:none}}
</style></head><body><nav aria-label="Rule references"><a href="player_guide.html">Player guide</a><a href="rules.html">Full rules</a><a href="index.html">Card gallery</a></nav><main${condensed ? ' class="condensed"' : ''}>${body}<footer>Generated from <a href="${source}">${source}</a>. Print this page from your browser.</footer></main></body></html>\n`;
}

const rules = await readFile(path.join(root, "RULES.md"), "utf8");
const guide = await readFile(path.join(root, "PLAYER_GUIDE.md"), "utf8");
for (const file of ["player_guide.html", "reference.html"]) await writeFile(path.join(root, file), page("Trick — Player Guide", render(guide), "PLAYER_GUIDE.md", true));
for (const file of ["rules.html", "trick_taking_rpg_rules_v4.html"]) await writeFile(path.join(root, file), page("Trick — Rules", render(rules), "RULES.md", false));
await writeFile(path.join(root, "trick_rules_reference.txt"), `CURRENT RULES — generated from RULES.md\n\n${rules}`);
const descriptions = ["CURRENT CARD TEXT — generated from card_rules.js", "Full procedures: RULES.md. Condensed guide: PLAYER_GUIDE.md.", ""];
for (const card of Object.values(globalThis.TrickCoreCards)) descriptions.push(`${card.title} (${card.suitLabel})`, ...card.lines, "");
await writeFile(path.join(root, "card_descriptions.txt"), descriptions.join("\n"));
console.log(`Built current HTML/text references and card descriptions. Player guide: ${guide.split(/\s+/).length} words.`);
