import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import "../card_rules.js";
import "../races/race_catalog.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const escape = text => text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const inline = text => escape(text)
  .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, href) => `<a href="${href === 'RULES.md' ? 'rules.html' : href === 'PLAYER_GUIDE.md' ? 'player_guide.html' : href}">${label}</a>`)
  .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
  .replace(/`([^`]+)`/g, "<code>$1</code>");

// The small Markdown subset used by the two rule documents; no runtime fetch.
function render(markdown) {
  const lines = markdown.trim().split(/\r?\n/);
  const result = [];
  for (let i = 0; i < lines.length;) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }
    const heading = line.match(/^(#{1,3}) (.+)$/);
    if (heading) { result.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`); i++; continue; }
    if (line.startsWith("|")) {
      const rows = [];
      while (i < lines.length && lines[i].startsWith("|")) rows.push(lines[i++].split("|").slice(1, -1).map(x => x.trim()));
      result.push(`<table><thead><tr>${rows[0].map(c => `<th>${inline(c)}</th>`).join("")}</tr></thead><tbody>${rows.slice(2).map(row => `<tr>${row.map(c => `<td>${inline(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`);
      continue;
    }
    if (/^(\d+\. |- )/.test(line)) {
      const ordered = /^\d/.test(line), tag = ordered ? "ol" : "ul", pattern = ordered ? /^\d+\. / : /^- /;
      const items = [];
      while (i < lines.length && pattern.test(lines[i])) items.push(`<li>${inline(lines[i++].replace(pattern, ""))}</li>`);
      result.push(`<${tag}>${items.join("")}</${tag}>`); continue;
    }
    const paragraph = [];
    while (i < lines.length && lines[i].trim() && !/^(#|\||\d+\. |- )/.test(lines[i])) paragraph.push(lines[i++]);
    if (!paragraph.length) throw new Error(`Unsupported Markdown: ${line}`);
    result.push(`<p>${inline(paragraph.join(" "))}</p>`);
  }
  return result.join("\n");
}

function page(title, body, source, condensed) {
  return `<!doctype html>
<!-- Generated by scripts/build_guides.mjs from ${source}; edit the Markdown source. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>
<style>
:root{color-scheme:light;--ink:#242b27;--accent:#356052;--line:#cbd6ce}*{box-sizing:border-box}body{margin:0;background:#f0f2ed;color:var(--ink);font:16px/1.5 Georgia,serif}nav{max-width:1040px;margin:24px auto;padding:0 28px;display:flex;gap:20px;font:14px/1.5 system-ui}a{color:var(--accent)}main{max-width:1040px;margin:0 auto 40px;padding:32px 44px 44px;background:#fffefa;border:1px solid var(--line)}h1,h2,h3,th{font-family:system-ui,sans-serif}h1{margin:0 0 22px;font-size:34px;letter-spacing:-1px}h2{font-size:18px;margin:24px 0 10px;color:var(--accent);break-after:avoid}h3{font-size:16px}p{margin:10px 0}ul,ol{padding-left:23px;margin:10px 0}li{margin:5px 0}table{width:100%;border-collapse:collapse;font-size:14px;margin:12px 0}th{text-align:left;background:#edf2ec}td,th{padding:8px 10px;border:1px solid var(--line);vertical-align:top}tr{break-inside:avoid}strong{font-weight:700}footer{margin-top:24px;border-top:1px solid var(--line);padding-top:12px;font:12px system-ui;color:#59675d}.condensed{font-size:15px}.condensed h2{margin-top:20px}@media(max-width:650px){nav{flex-wrap:wrap;margin:16px auto;padding:0 18px;gap:12px}main{padding:24px 18px;border:0}h1{font-size:28px}table{font-size:12px}td,th{padding:6px}}@page{size:A4;margin:13mm}@media print{body{background:white;font-size:10pt;line-height:1.35}nav,footer{display:none}main{border:0;padding:0;margin:0;max-width:none}.condensed{font-size:9.5pt}h1{font-size:23pt;margin-bottom:12pt}h2,.condensed h2{font-size:12pt;margin:13pt 0 6pt}p,ul,ol{margin:6pt 0}li{margin:3pt 0}table{font-size:9pt;margin:7pt 0}td,th{padding:5pt}a{color:inherit;text-decoration:none}}
</style></head><body><nav aria-label="Rule references"><a href="player_guide.html">Player guide</a><a href="rules.html">Full rules</a><a href="index.html">Card gallery</a></nav><main${condensed ? ' class="condensed"' : ''}>${body}<footer>Generated from <a href="${source}">${source}</a>. Print this page from your browser.</footer></main></body></html>\n`;
}

// race_mechanics.html is generated from races/race_catalog.js, the same source
// the reference cards and the gallery use; edit the catalog, not this page.
const raceStyle = `:root{--paper:#efe4cf;--paper-shadow:#dcc9ab;--ink:#2f2419;--muted:#665746;--pine:#40543e;--clay:#8a4f37;--gold:#a57c2f;--line:rgba(47,36,25,0.18);--panel:rgba(255,250,240,0.72)}*{box-sizing:border-box}body{margin:0;font-family:Georgia,"Times New Roman",serif;color:var(--ink);background:radial-gradient(circle at top,rgba(255,248,233,0.82),transparent 38%),linear-gradient(180deg,#6e8362 0%,#4f6049 22%,#7a624b 22.5%,#664d39 100%);min-height:100vh}.page{width:min(980px,calc(100% - 32px));margin:32px auto;padding:32px;background:var(--paper);border:1px solid var(--paper-shadow);box-shadow:0 18px 50px rgba(26,18,12,0.28);position:relative}.page::before{content:"";position:absolute;inset:12px;border:1px solid rgba(101,77,51,0.18);pointer-events:none}header{padding-bottom:20px;border-bottom:2px solid var(--pine)}h1,h2{margin:0;font-weight:600;line-height:1.1}h1{font-size:clamp(2.1rem,4vw,3.1rem)}h2{margin-bottom:10px;font-size:1.4rem;color:var(--pine)}p{margin:0;line-height:1.65;font-size:1.03rem}p+p{margin-top:10px}a{color:var(--clay)}.section{margin-top:24px;padding:18px 22px;background:var(--panel);border:1px solid var(--line);border-left:6px solid var(--gold)}.section.plain{margin-top:26px;padding:0;background:none;border:0}.flavor{color:var(--muted);font-style:italic}.tag{display:inline-block;margin:0 8px 10px 0;padding:3px 8px;border:1px solid var(--line);color:var(--pine);background:rgba(255,255,255,0.45);font-size:0.76rem;letter-spacing:0.04em;text-transform:uppercase}.card-line{margin-top:12px;font-size:0.92rem}@media(max-width:640px){.page{width:calc(100% - 20px);margin:10px auto;padding:20px}}`;

function raceSection(entry) {
  const tags = entry.tags.map(tag => `<span class="tag">${escape(tag)}</span>`).join("");
  const body = entry.rules.map(rule => `<p>${escape(rule)}</p>`).join("");
  return `<section class="section" id="${entry.id}"><h2>${escape(entry.name)} — ${escape(entry.abilityTitle)}</h2>${tags}<p class="flavor">${escape(entry.flavor)}</p>${body}<p class="card-line"><a href="races/race_card.html?id=${entry.id}">Reference card</a></p></section>`;
}

const { raceEntries, sharedTiming } = globalThis.TrickRaceCatalog;
const racePage = `<!doctype html>
<!-- Generated by scripts/build_guides.mjs from races/race_catalog.js; edit the catalog. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Optional peoples of Black Valley</title>
<style>${raceStyle}</style></head><body><main class="page">
<header><h1>Optional peoples of Black Valley</h1><p>Use with <a href="rules.html">the current rules</a>. These setting abilities are optional additions, not part of the <a href="player_guide.html">condensed player guide</a>. Every ability here is printed on a <a href="index.html">reference card</a>.</p></header>
${raceSection(sharedTiming)}
${raceEntries.map(entry => raceSection(entry)).join("\n")}
<section class="section plain"><h2>Setting</h2><p><a href="setting_races.html">The six peoples</a> · <a href="black_valley_setting.html">Black Valley</a> · <a href="session0_town_questions.html">Session 0 questions</a></p></section>
</main></body></html>
`;
await writeFile(path.join(root, "race_mechanics.html"), racePage);

const rules = await readFile(path.join(root, "RULES.md"), "utf8");
const guide = await readFile(path.join(root, "PLAYER_GUIDE.md"), "utf8");
for (const file of ["player_guide.html", "reference.html"]) await writeFile(path.join(root, file), page("Trick — Player Guide", render(guide), "PLAYER_GUIDE.md", true));
for (const file of ["rules.html", "trick_taking_rpg_rules_v4.html"]) await writeFile(path.join(root, file), page("Trick — Rules", render(rules), "RULES.md", false));
await writeFile(path.join(root, "trick_rules_reference.txt"), `CURRENT RULES — generated from RULES.md\n\n${rules}`);
const descriptions = ["CURRENT CARD TEXT — generated from card_rules.js", "Full procedures: RULES.md. Condensed guide: PLAYER_GUIDE.md.", ""];
for (const card of Object.values(globalThis.TrickCoreCards)) descriptions.push(`${card.title} (${card.suitLabel})`, ...card.lines, "");
await writeFile(path.join(root, "card_descriptions.txt"), descriptions.join("\n"));
console.log(`Built current HTML/text references and card descriptions. Player guide: ${guide.split(/\s+/).length} words.`);
