// RULES.md is the single source for rules text. This module reads the card-facing parts of it:
// the Consolations and Statuses tables and the Blessed rule list, which the card faces print.
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const rulesPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "RULES.md");

// Status keys follow the card pages' file names (Stumble lives in dazed.html).
const STATUS_KEYS = { Stumble: "dazed" };
const plain = (text) => text.replace(/\*\*(.+?)\*\*/g, "$1").trim();

function section(markdown, heading) {
  const lines = markdown.split(/\r?\n/);
  const start = lines.findIndex((line) => line === `## ${heading}`);
  if (start < 0) throw new Error(`RULES.md has no "## ${heading}" section`);
  const end = lines.findIndex((line, index) => index > start && line.startsWith("## "));
  return lines.slice(start + 1, end < 0 ? undefined : end);
}

function tableRows(lines, heading) {
  const rows = lines.filter((line) => line.startsWith("|")).slice(2)
    .map((line) => line.split("|").slice(1, -1).map((cell) => cell.trim()));
  if (!rows.length) throw new Error(`RULES.md "## ${heading}" has no table`);
  return rows;
}

export function cardsFromRules(markdown) {
  // "Strength — Hearts" rows give each suit's standard-deck name.
  const standard = Object.fromEntries(tableRows(section(markdown, "Decks and suits"), "Decks and suits")
    .map(([suit]) => suit.split(" — ").map((part) => part.trim())));
  const cards = {};

  for (const [label, effect] of tableRows(section(markdown, "Consolations"), "Consolations")) {
    const [suit, name] = plain(label).split(" — ");
    const text = plain(effect);
    cards[suit.toLowerCase()] = {
      suitLabel: `${standard[suit]} — ${suit}`, domain: `${standard[suit]} / Consolation`, title: name.toUpperCase(),
      lines: [text], description: text
    };
  }

  for (const [label, effect] of tableRows(section(markdown, "Statuses"), "Statuses")) {
    const [name, suit] = plain(label).split(" — ");
    const text = plain(effect);
    cards[STATUS_KEYS[name] || name.toLowerCase()] = {
      suitLabel: `${standard[suit]} — ${name}`, domain: `${standard[suit]} / Status`, title: name.toUpperCase(),
      lines: [text], description: text
    };
  }

  const blessed = section(markdown, "Blessed").filter((line) => line.startsWith("- ")).map((line) => plain(line.slice(2)));
  if (!blessed.length) throw new Error('RULES.md "## Blessed" has no rule list');
  cards.blessed = {
    suitLabel: "Joker — Blessed", domain: "Joker / Blessed", title: "BLESSED",
    lines: blessed, description: blessed[0]
  };
  return cards;
}

export function cardRulesModule(cards) {
  return `// Generated by scripts/build_guides.mjs from RULES.md. Edit RULES.md, then run npm run build:guides.
globalThis.TrickCoreCards = ${JSON.stringify(cards, null, 2)};
`;
}

export async function readRules() {
  return readFile(rulesPath, "utf8");
}
